require_relative 'config/environment'
require 'sinatra/activerecord/rake'
require_relative 'emp'


desc "Runs a console session"
task :console do
  ActiveRecord::Base.logger = Logger.new(STDOUT)
  Pry.start
end
